# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AGPU' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AGPU
  pod 'Alamofire'
  pod 'FSCalendar'
  pod 'SDWebImage'
  pod 'SnapKit'

end
